package org.junjun.util.java.persistence;
// Generated Jun 6, 2017 10:36:31 PM by Hibernate Tools 5.2.3.Final


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Role generated by hbm2java
 */
@Entity
@Table(name="ROLE"
    ,catalog="MYDB"
)
public class Role  implements java.io.Serializable {


     private BigDecimal id;
     private User user;
     private String name;

    public Role() {
    }

    public Role(BigDecimal id, User user, String name) {
       this.id = id;
       this.user = user;
       this.name = name;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false, scale=0)
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="FK_USER_ID", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    
    @Column(name="NAME", nullable=false, length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


